name: Publish release
on:
  push:
    branches:
      - publish
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.6.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2#

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Publish to Ossrh
        run: ./gradlew publishAllPublicationsToOssrhRepository

      - name: Publish to Modrinth
        run: ./gradlew :silk-all:modrinth
